# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-03 12:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=400)),
                ('testcases', models.TextField(max_length=10000)),
                ('testcases_output', models.TextField(default='', max_length=10000)),
                ('inputs', models.TextField(max_length=50000)),
                ('points', models.PositiveIntegerField(default=100)),
                ('right_count', models.PositiveIntegerField(default=0)),
                ('wrong_count', models.PositiveIntegerField(default=0)),
                ('output', models.TextField(max_length=10000)),
            ],
        ),
        migrations.CreateModel(
            name='Track',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='question',
            name='track',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='practice.Track'),
        ),
    ]
