# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-04 18:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('practice', '0002_auto_20170903_2359'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='testcases',
            field=models.TextField(max_length=100),
        ),
        migrations.AlterField(
            model_name='question',
            name='testcases_output',
            field=models.TextField(default='', max_length=100),
        ),
    ]
