# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-04 20:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('practice', '0003_auto_20170904_2337'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='explaination',
            field=models.TextField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='description',
            field=models.TextField(max_length=1000, null=True),
        ),
    ]
