# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-04 20:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('practice', '0004_auto_20170905_0144'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='explaination',
            new_name='explanation',
        ),
    ]
