# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-01 16:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compiler', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=400)),
                ('testcases', models.TextField(max_length=10000)),
                ('inputs', models.TextField(max_length=50000)),
                ('points', models.PositiveIntegerField(default=100)),
                ('right_count', models.PositiveIntegerField(default=0)),
                ('wrong_count', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.DeleteModel(
            name='Template',
        ),
    ]
