# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-01 16:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compiler', '0002_auto_20170901_2151'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='output',
            field=models.TextField(default='temp', max_length=10000),
            preserve_default=False,
        ),
    ]
