# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-03 09:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compiler', '0003_question_output'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='testcases_output',
            field=models.TextField(default='', max_length=10000),
        ),
    ]
