# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-03 12:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('compiler', '0004_question_testcases_output'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Question',
        ),
    ]
