# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-05 18:10
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('practice', '0006_auto_20170905_0203'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Contest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, max_length=1000)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='ContestQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=400)),
                ('description', models.TextField(max_length=1000, null=True)),
                ('testcases', models.TextField(max_length=100)),
                ('testcases_output', models.TextField(blank=True, max_length=100)),
                ('explanation', models.TextField(blank=True, max_length=1000)),
                ('inputs', models.TextField(max_length=50000)),
                ('output', models.TextField(max_length=10000)),
                ('points', models.PositiveIntegerField(default=100)),
                ('right_count', models.PositiveIntegerField(default=0)),
                ('wrong_count', models.PositiveIntegerField(default=0)),
                ('contest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ContestQuestionContest', to='contests.Contest')),
                ('track', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ContestQuestionTrack', to='practice.Track')),
            ],
        ),
        migrations.CreateModel(
            name='ContestRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ContestRecordContest', to='contests.Contest')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ContestRecordQuestion', to='contests.ContestQuestion')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ContestRecordUser', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Leaderboard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contests.Contest')),
            ],
        ),
    ]
