# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-07 12:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0002_remove_contestrecord_contest'),
    ]

    operations = [
        migrations.AddField(
            model_name='contestrecord',
            name='contest',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='ContestRecordContest', to='contests.Contest'),
            preserve_default=False,
        ),
    ]
