# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-07 20:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0003_contestrecord_contest'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaderboard',
            name='leaderboard',
            field=models.CharField(default='[]', max_length=1000),
        ),
    ]
