# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-16 13:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0004_leaderboard_leaderboard'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaderboard',
            name='total_points',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
