# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-12-30 18:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0005_leaderboard_total_points'),
    ]

    operations = [
        migrations.AddField(
            model_name='contest',
            name='image',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='contest',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
